feat: enforce dependencies for services in docker compose
ashirt-ops/ashirt-server pull request #1047
Opened 2024-02-22 22:37 UTC by luk3skyw4lker

Adding dependencies and health checks for relevant services

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

Resolve #1012

2024-02-22 22:43 UTC, jrozner requested changes
I think the nginx container needs to depend on the backend one because it checks the upstream exists at startup.

2024-02-23 15:52 UTC, luk3skyw4lker commented
@jrozner Isn't that the case already? All the frontend (nginx) containers depends on the backend to be up already

2024-02-23 15:58 UTC, jrozner commented
Ah sorry, I didn't realize we already had that.

2024-02-23 19:47 UTC, jkennedyvz approved these changes

2024-02-23 21:06 UTC, jkennedyvz approved these changes

2024-02-24 05:43 UTC, jrozner approved these changes

2024-02-27 00:53 UTC, merged