ensure only one key is deleted if multiple with same name
ashirt-ops/ashirt-server pull request #862
Opened 2023-06-15 19:31 UTC by TylerNoblett

Ensure that if there are multiple keys with the same name, only one is deleted

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

2023-07-19 17:04 UTC, JoelAtDeluxe commented on backend/helpers/functional.go
> +// Filter is a generic function that searches through a list searching for all items that match
Oops!

2023-07-24 18:06 UTC, jrozner requested changes
It looks like this would remove the first key rather than the one selected. I think it would make sense to either add a unique constraint on the name (so this problem doesn't exist) or swap out the identifier in the DELETE request to be a unique identifier (like we do with slugs) so that we can target them directly.

2023-07-24 18:08 UTC, TylerNoblett commented
> It looks like this would remove the first key rather than the one selected. I think it would make sense to either add a unique constraint on the name (so this problem doesn't exist) or swap out the identifier in the DELETE request to be a unique identifier (like we do with slugs) so that we can target them directly.

oh that's a good point - yeah I feel like the first one makes the most sense. I'll take a look

2023-07-25 19:27 UTC, TylerNoblett commented
@jrozner we're now deleting based on the unique credential ID instead of the name

2023-07-26 22:19 UTC, jkennedyvz approved these changes

2023-08-31 17:52 UTC, TylerNoblett commented
@jrozner @jkennedyvz I just added a check to ensure that the username is unique

2023-09-22 19:07 UTC, jrozner approved these changes

2023-09-22 19:07 UTC, merged